use_frameworks!

ios_deployment_target = '13.0'

target 'VMKit_Example' do
  pod 'VMKit', :path => '../'
  pod 'ViewModel', :path => '../../ViewModel'
  pod 'VMLocalization', :path => '../../VMLocalization'
  pod 'Masonry'

  target 'VMKit_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end

post_install do |installer_or_rep|
  installer = installer_or_rep.respond_to?(:installer) ? installer_or_rep.installer : installer_or_rep
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |configuration|
      target.build_settings(configuration.name)['IPHONEOS_DEPLOYMENT_TARGET'] = ios_deployment_target
    end
  end
end
